[package]
name = "strata-p2p"
version = "0.1.0"
edition = "2021"

[features]
default = ["request-response", "quic", "gossipsub"]
request-response = ["libp2p/request-response"]
quic = ["libp2p/quic"]
gossipsub = ["libp2p/gossipsub"]

[lints]
rust.missing_debug_implementations = "warn"
rust.unreachable_pub = "warn"
rust.unused_crate_dependencies = "deny"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = { level = "deny", priority = -1 }

[dependencies]
asynchronous-codec.workspace = true
crossbeam-deque.workspace = true
dashmap.workspace = true
futures.workspace = true
libp2p = { workspace = true, features = [
  "noise",
  "tcp",
  "tokio",
  "ed25519",
  "macros",
  "yamux",
  "identify",
] }
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
tracing.workspace = true


[dev-dependencies]
anyhow = "1.0.95"
rand = "0.9.1"
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
tokio-util.workspace = true
tracing-subscriber.workspace = true
