[package]
name = "strata-p2p"
version.workspace = true
edition.workspace = true

[features]
default = ["request-response", "quic", "gossipsub", "kad"]
request-response = ["libp2p/request-response"]
quic = ["libp2p/quic"]
gossipsub = ["libp2p/gossipsub"]
kad = ["libp2p/kad"]

[lints]
workspace = true

[dependencies]
asynchronous-codec.workspace = true
cynosure.workspace = true
futures.workspace = true
libp2p = { workspace = true, features = [
  "noise",
  "tcp",
  "tokio",
  "ed25519",
  "macros",
  "yamux",
  "identify",
  "serde",
] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
tracing.workspace = true


[dev-dependencies]
anyhow = "1.0.95"
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
tokio-util.workspace = true
tracing-subscriber.workspace = true
