[package]
name = "strata-p2p"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
libp2p = { workspace = true, features = [
  "noise",
  "gossipsub",
  "tcp",
  "request-response",
  "tokio",
  "ed25519",
  "macros",
  "yamux",
  "identify",
] }

futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
tracing.workspace = true
hex = { workspace = true, features = ["serde"] }
serde.workspace = true


[dev-dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
tokio-util.workspace = true
tracing-subscriber.workspace = true
anyhow = "1.0.95"
