[package]
name = "strata-p2p"
version.workspace = true
edition.workspace = true

[features]
default = ["request-response", "kademlia"]
request-response = []
kademlia = []

[lints]
workspace = true

[dependencies]
asynchronous-codec.workspace = true
libp2p = { workspace = true, features = [
  "noise",
  "gossipsub",
  "tcp",
  "request-response",
  "tokio",
  "ed25519",
  "macros",
  "yamux",
  "identify",
  "kad",
] }
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
anyhow = "1.0.95"
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
tokio-util.workspace = true
tracing-subscriber.workspace = true
