name: feature-matrix

on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      RUST_LOG:
        description: "Log level"
        required: false
        default: "warn"
        type: string

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  extract-rust-version:
    name: extract-toolchain-version
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.extract-version.outputs.nightly-version }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: extract-rust-version
        id: extract-version
        uses: ./.github/actions/extract-rust-version

  test:
    name: test (feature matrix)
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        feature_byos: ["byos",""]
        feature_kad: ["kad",""]
        feature_request-response: ["request-response",""]
        feature_gossipsub: ["gossipsub",""]
        feature_quic: ["quic",""]
        feature_mem-conn-limits-abs: ["mem-conn-limits-abs",""]
        feature_mem-conn-limits-rel: ["mem-conn-limits-rel",""]
        exclude:
          - feature_kad: "kad"
            feature_byos: "byos"

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: install-rust
        uses: dtolnay/rust-toolchain@b95584d8105b9ab200e15821fa671848cf2b7017 # nightly
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.nightly-version }}

      - name: install-nextest
        uses: taiki-e/install-action@ba0a04e0afd83836a25f30f6f33e6ebdd81a8ff1 # v2
        with:
          tool: nextest@0.9.98

      - name: rust-cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
        with:
          cache-on-failure: true

      - name: set env var for this job
        run: |
          printf 'FEATURES=%s' "$(printf '${{ toJson(matrix) }}' | jq -r '.[]' | xargs )" >> "${GITHUB_ENV}"

      - name: show config
        run: |
          printf 'Features: "%s"' "${FEATURES}"

      - name: run tests (no features)
        if: ${{ env.FEATURES == '' }}
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: ${{ github.event.inputs.RUST_LOG || 'warn' }}
        run: |
          cargo nextest run --workspace --no-capture --no-default-features

      - name: run tests (feature combo)
        if: ${{ env.FEATURES != '' }}
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: ${{ github.event.inputs.RUST_LOG || 'warn' }}
        run: |
          cargo nextest run --workspace --no-capture --no-default-features --features "${FEATURES}"
