name: feature-matrix

on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      RUST_LOG:
        description: "Log level"
        required: false
        default: "warn"
        type: string

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  extract-rust-version:
    name: extract-toolchain-version
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.extract-version.outputs.nightly-version }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: extract-rust-version
        id: extract-version
        uses: ./.github/actions/extract-rust-version

  test:
    name: test (${{ matrix.name }})
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          # Non-BYOS single-feature
          - name: non-byos | base
            features: ""
          - name: non-byos | gossipsub
            features: "gossipsub"
          - name: non-byos | request-response
            features: "request-response"
          - name: non-byos | quic
            features: "quic"
          - name: non-byos | kad
            features: "kad"
          # Non-BYOS dual-feature
          - name: non-byos | gossipsub + request-response
            features: "gossipsub request-response"
          - name: non-byos | gossipsub + quic
            features: "gossipsub quic"
          - name: non-byos | gossipsub + kad
            features: "gossipsub kad"
          - name: non-byos | request-response + quic
            features: "request-response quic"
          - name: non-byos | request-response + kad
            features: "request-response kad"
          - name: non-byos | quic + kad
            features: "quic kad"
          # Non-BYOS triple-feature
          - name: non-byos | gossipsub + request-response + quic
            features: "gossipsub request-response quic"
          - name: non-byos | gossipsub + request-response + kad
            features: "gossipsub request-response kad"
          - name: non-byos | gossipsub + quic + kad
            features: "gossipsub quic kad"
          - name: non-byos | request-response + quic + kad
            features: "request-response quic kad"
          # Non-BYOS all
          - name: non-byos | all (gossipsub + request-response + quic + kad)
            features: "gossipsub request-response quic kad"
          # BYOS single-feature
          - name: byos | base
            features: "byos"
          - name: byos | gossipsub
            features: "byos gossipsub"
          - name: byos | request-response
            features: "byos request-response"
          - name: byos | quic
            features: "byos quic"
          # BYOS dual-feature (with BYOS)
          - name: byos | gossipsub + request-response
            features: "byos gossipsub request-response"
          - name: byos | gossipsub + quic
            features: "byos gossipsub quic"
          - name: byos | request-response + quic
            features: "byos request-response quic"
          # BYOS all supported (no kad)
          - name: byos | all (gossipsub + request-response + quic)
            features: "byos gossipsub request-response quic"

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: install-rust
        uses: dtolnay/rust-toolchain@b95584d8105b9ab200e15821fa671848cf2b7017 # nightly
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.nightly-version }}

      - name: install-nextest
        uses: taiki-e/install-action@ba0a04e0afd83836a25f30f6f33e6ebdd81a8ff1 # v2
        with:
          tool: nextest@0.9.98

      - name: rust-cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
        with:
          cache-on-failure: true

      - name: show config
        run: |
          echo "Matrix features: '${{ matrix.features }}'"

      - name: run tests (no features)
        if: ${{ matrix.features == '' }}
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: ${{ github.event.inputs.RUST_LOG || 'warn' }}
        run: |
          cargo nextest run --workspace --no-capture --no-default-features

      - name: run tests (feature combo)
        if: ${{ matrix.features != '' }}
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: ${{ github.event.inputs.RUST_LOG || 'warn' }}
        run: |
          cargo nextest run --workspace --no-capture --no-default-features --features "${{ matrix.features }}"
