name: lint

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  extract-rust-version:
    name: Extract toolchain version
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.extract-version.outputs.nightly-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Extract Rust version
        id: extract-version
        uses: ./.github/actions/extract-rust-version

  clippy:
    name: clippy (feature matrix)
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        feature_byos: ["byos",""]
        feature_kad: ["kad",""]
        feature_request-response: ["request-response",""]
        feature_gossipsub: ["gossipsub",""]
        feature_quic: ["quic",""]
        feature_mem-conn-limits-abs: ["mem-conn-limits-abs",""]
        feature_mem-conn-limits-rel: ["mem-conn-limits-rel",""]
        exclude:
          - feature_kad: "kad"
            feature_byos: "byos"

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: install-rust
        uses: dtolnay/rust-toolchain@b95584d8105b9ab200e15821fa671848cf2b7017 # nightly
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.nightly-version }}
      - name: rust-cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
        with:
          cache-on-failure: true

      - name: set env var for this job
        run: |
          printf 'FEATURES=%s' "$(printf '${{ toJson(matrix) }}' | jq -r '.[]' | xargs )" >> "${GITHUB_ENV}"

      - name: show config
        run: |
          echo "Clippy combo: '${{ toJson(matrix) }}'"
          printf 'Features: "%s"' "${FEATURES}"

      - name: clippy (no features)
        if: ${{ env.FEATURES == '' }}
        env:
          RUSTFLAGS: -D warnings
        run: |
          cargo clippy --workspace --lib --locked --examples --tests --benches --all-targets --no-default-features

      - name: clippy (with features)
        if: ${{ env.FEATURES != '' }}
        env:
          RUSTFLAGS: -D warnings
        run: |
          cargo clippy --workspace --lib --locked --examples --tests --benches --all-targets --no-default-features --features "${FEATURES}"

  fmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@b95584d8105b9ab200e15821fa671848cf2b7017 # nightly
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.nightly-version }}
          components: rustfmt

      - name: cargo fmt check
        run: cargo fmt --all --check

  codespell:
    name: Check code spellings
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Run codespell
        uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2

  taplo:
    name: Lint and check formatting of TOML files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz \
            | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Run taplo lint
        run: |
          taplo lint

      - name: Run taplo format check
        run: |
          taplo fmt --check

  lint-success:
    name: Check that lints passed
    runs-on: ubuntu-latest
    if: always()
    needs:
      - clippy
      - fmt
      - codespell
      - taplo
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
