name: Lint GitHub Actions workflows
on:
  pull_request:
    paths:
      - ".github/**"
  merge_group:
  push:
    paths:
      - ".github/**"

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@08ef4afa963243489a457cca426f705ce4e0d1a5 # v1.60
        with:
          fail_level: "any"
