# Runs unit tests.

name: Unit Tests

on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      RUST_LOG:
        description: "Log level"
        required: false
        default: "info"
        type: string

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  extract-rust-version:
    name: Extract toolchain version
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.extract-version.outputs.nightly-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Extract Rust version
        id: extract-version
        uses: ./.github/actions/extract-rust-version

  test:
    name: Run unit tests and generate report
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 60 # better fail-safe than the default 360 in github actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@b95584d8105b9ab200e15821fa671848cf2b7017 # nightly
        with:
          components: llvm-tools-preview
          toolchain: ${{ needs.extract-rust-version.outputs.nightly-version }}

      - name: Install latest nextest release
        uses: taiki-e/install-action@ba0a04e0afd83836a25f30f6f33e6ebdd81a8ff1 # v2
        with:
          tool: nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@ba0a04e0afd83836a25f30f6f33e6ebdd81a8ff1 # v2
        with:
          tool: cargo-llvm-cov

      - name: Rust cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
        with:
          cache-on-failure: true

      - name: Run tests with coverage
        run: |
          cargo llvm-cov --workspace nextest --profile ci --no-capture --lcov --output-path lcov.info
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: ${{ github.event.inputs.RUST_LOG || 'warn' }}

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2
        if: always()
        with:
          paths: "target/nextest/ci/junit.xml"

      - name: Publish Test Coverage
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          files: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  unit-success:
    name: Check that unit tests pass
    runs-on: ubuntu-latest
    if: always()
    needs: [test]
    timeout-minutes: 60
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
